const int ECRAN_LATIME = 800;
const int ECRAN_INALTIME = 600;
const int LATURA_TABLA = 500;
const int LATURA_CASUTA = 100;
const int START_SUS = (ECRAN_INALTIME - LATURA_TABLA)/2;
const int START_STANGA = (ECRAN_LATIME - LATURA_TABLA)/2;


#define CASUTA_GOALA 0
#define CASUTA_IEPURE 1
#define CASUTA_CIUPERCA 2
#define CASUTA_VULPE_CAP_ORIZ 3
#define CASUTA_VULPE_COADA_ORIZ 4
#define CASUTA_VULPE_CAP_VERT 5
#define CASUTA_VULPE_COADA_VERT 6
#define CASUTA_HIGHLIGHT 7
#define CASUTA_HIGHLIGHT_REMOVE 8
#define CASUTA_GAURA 9

#define CULOARE_FUNDAL GREEN
#define CULOARE_HIGHLIGHT WHITE
#define CULOARE_HIGHLIGHT_REMOVE BLACK
