#include <iostream>
#include <fstream>
#include <graphics.h>
#include <winbgim.h>
#include <conio.h>
#include <stdlib.h>
#include <stdio.h>
#include "graphics.h"
#include <dos.h>
#include <mmsystem.h>
